#!/bin/bash

from_path=$(dirname $0)
src=$(realpah $from_path/Xdefaults-retina15.4)

in=$(realpath $from_path/$1)
if [[ -e $in ]]
then
    src=$in
fi
dst=$(realpath $from_path/Xdefaults)
cp $src $dst


for i in Xdefaults Xmodmap xinitrc xmobarrc xmonad/xmonad.hs xsession
do
    src=$(realpath $from_path/$i)
    install -vD -m 400 $src ${HOME}/.$i || exit 1
done

xmonad --recompile
pkill xmobar
sleep 1
xmonad --restart

exit 0
