#!/bin/bash

Xdefaults='Xdefaults-retina15.4'

if [[ -e $1 ]]
then
    Xdefaults=$1
fi
cp $Xdefaults Xdefaults

from_path=$(dirname $0)

for i in Xdefaults Xmodmap xinitrc xmobarrc xmonad/xmonad.hs xsession
do
    src=$(realpath $from_path/$i)
    install -vD -m 400 $src ${HOME}/.$i || exit 1
done

xmonad --recompile
xmonad --restart

exit 0
