#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# Keyboard Mapping
usermodmap=$HOME/.Xmodmap

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
    xkbset m
    xkbset exp =m
fi
#setxkbmap -layout "$(setxkbmap -print | awk -F + '/xkb_symbols/ {print $2}')" -option ctrl:nocaps

# Enable dual head if two monitors
screens=`xrandr -q | grep ' connected' | wc -l`
if [[ 2 == $screens ]]
then
    xrandr --output DVI-0 --mode 1680x1050 --left-of DVI-1
fi

# Enable screen saver
nohup xscreensaver -nosplash &

# Enable auto-suspend (lock requires UPower, PolicyKit, and xscreensaver)
xautolock -time 5 -locker $HOME/bin/lock &

# Enable fancy effects
xcompmgr -c -f -C -F &

# use a real cursor
xsetroot -cursor_name left_ptr

# set a wallpaper
feh --bg-fill ~/.config/wallpaper

# enable ssh-agent per-session
eval $(ssh-agent)

# Load Xresources
#xrdb -merge ~/.Xresources

# Set default screen brightness
xbacklight =20

# Launch xmonad
xmonad

exit 0
